services:
  app:
    image: crpi-fmn9v2rn38d84ou1.cn-shanghai.personal.cr.aliyuncs.com/axelwt/resume-gpt:latest
    build: .
    expose:
      - "8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
