services:
  app:
    image: ghcr.io/axelwt/resume-gpt:latest
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
